name: Proxy Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

permissions:
  contents: write

jobs:
  check-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies and Xray
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install requests

          # Скачиваем конкретный релиз Xray (можно поменять версию)
          XZIP="Xray-linux-64.zip"
          wget -q -O "${XZIP}" "https://github.com/XTLS/Xray-core/releases/download/v1.8.4/Xray-linux-64.zip"
          unzip -o "${XZIP}"

          # Ищем бинарник xray в текущей директории/подпапках
          XRAY_BIN=$(find . -maxdepth 3 -type f -name xray -print -quit || true)
          if [ -z "${XRAY_BIN}" ]; then
            echo "xray binary not found after unzip"
            ls -la
            exit 1
          fi

          sudo mv "${XRAY_BIN}" /usr/local/bin/xray
          sudo chmod +x /usr/local/bin/xray

          # Очистка временных файлов архива (если есть geosite/geoip — удаляем только из рабочей директории)
          rm -f "${XZIP}" || true
          # (геодатасеты возможно нужны — удаляйте только если уверены)
          rm -f ./geoip.dat ./geosite.dat || true

      - name: Run proxy checker
        env:
          XRAY_PATH: /usr/local/bin/xray
        run: |
          set -euo pipefail
          # Создаем/перезаписываем символьную ссылку для совместимости со скриптом
          sudo ln -sf /usr/local/bin/xray /usr/local/bin/xray.exe
          # Запускаем скрипт (unbuffered чтобы логи шли сразу)
          python -u proxy_checker.py

      - name: Commit results
        run: |
          set -euo pipefail
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Добавляем только файлы результатов, чтобы не закоммитить лишнее
          git add -- '*_working_proxies*.txt' || echo "No result files to add"
          git commit -m "Update proxy lists" || echo "No changes to commit"
          git push
